### ISSUE TITLE
Broken after updating to 0.7.4

### ISSUE THREAD

**Issue by scheemik** [bus-stop/Termination#100]
I updated to version 0.7.4 and now the terminal window will show up, but with no prompt. Just a blinking cursor but I can't enter any text

**Comment by the-j0k3r** [comment]
@scheemik uninstall and reinstall with latest Atom and latest Termination.

**Comment by the-j0k3r** [comment]
Fixed anywho with https://github.com/bus-stop/Termination/commit/0e4a3dc6691b65c171e46b6e22b8f292a08c4971
