### ISSUE TITLE
Prevent keys bound in Atom from being captured by xterm.js

### ISSUE THREAD

**Issue by allefeld** [bus-stop/Termination#105]
I would like to use a function key (F4) to toggle the terminal:

```
'atom-workspace':
  'f4': 'termination:toggle'
```

This works to open a terminal, but not to hide it again. I believe the reason is that `xterm.js` captures the keyboard event, because F4 is one of the keys that can be translated into an escape sequence.

`xterm.js` provides a way to intercept its keyboard event capture: [attachCustomKeyEventHandler](https://xtermjs.org/docs/api/terminal/classes/terminal/#attachcustomkeyeventhandler). I propose to use this feature to intercept all those keypresses for which a binding is configured in Atom. Whether that is the case can be checked with [findKeyBindings](https://flight-manual.atom.io/api/v1.43.0/KeymapManager/#instance-findKeyBindings).

**Comment by the-j0k3r** [comment]
Neither termination nor [terminus ](https://github.com/bus-stop/terminus) nor platformio-ide-terminal support xterm.js

**Comment by allefeld** [comment]
Sorry, my mistake.
