### ISSUE TITLE
[FR] : Open terminal at right side instead of bottom

### ISSUE THREAD

**Issue by rng70** [bus-stop/Termination#112]
When a new terminal is opened currently it is opening at the bottom of the editor. Suppose 
![image](https://user-images.githubusercontent.com/45529910/83188956-4a0d5780-a152-11ea-8a1f-da0e332c4c20.png)
)
but it will be helpful if it is opened at the right side instead of bottom. I'm sorry I can't provide any additional image because I don't have a right-side panel based photo.

**Comment by UziTech** [comment]
You can try [x-terminal](https://atom.io/packages/x-terminal), which allows you to move the terminal to any panel or dock.

**Comment by rng70** [comment]
@UziTech thanks ... actually I was looking for it ... for both cased I have seen that both was developed by bus-stop and so I am closing this [FR]. again  thank you.
