### ISSUE TITLE
[Q] Is it possible to run "atom" command from termination terminal?

### ISSUE THREAD

**Issue by sveiaam** [bus-stop/Termination#116]
### I would like to be able do the following

1. I would like to run the 'atom' command to open (and then edit) files from the termination terminal.
2. Most commands I have tried in the termination terminal works, but specifically those starting with 'atom' give the error message: "need to run as root or suid"
3. Running "sudo atom ..." yields the error message "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?"
4. When running these commands in an external terminal window (gnome terminal) they run exactly as you would expect.
5. Is this intended behaviour? How can I give sufficient privileges to the termination terminal? Elsewise, is there any similar terminal packages that allows this?

**Comment by UziTech** [comment]
Looks like you are running into this error: https://github.com/bus-stop/terminus/issues/84

**Comment by sveiaam** [comment]
Yes. But why does atom need sudo privileges in the first place? It does not need sudo to be called with the recular terminal.

**Comment by UziTech** [comment]
Not sure. I am on windows and it seems to work fine for me.

**Comment by the-j0k3r** [comment]
> Yes. But why does atom need sudo privileges in the first place? It does not need sudo to be called with the recular terminal.

Its an electron 5.0.13 issue, a fix has been merged into atom and will be available in 1.52.0-beta0 and later releases.

**Comment by sveiaam** [comment]
Aight, thanks for the replies!
