### ISSUE TITLE
[BR] trims the last characters from the bottom if the caret is at the very bottom of the screen

### ISSUE THREAD

**Issue by dayloks** [bus-stop/Termination#118]
trims the last characters from the bottom if the caret is at the very **bottom of the screen**
(if you print underscores, they are not displayed at all)

**Comment by UziTech** [comment]
Can you give us steps to reproduce this? versions of os/atom/termination? a gif showing the behavior would also help.

**Comment by dayloks** [comment]
win7
atom 1.52.0 x64
termination 0.7.6

the problem has been corrected as follows:
styles.less

div.terminal {
	top:-5px;
	margin-top: 5px;
}
