### ISSUE TITLE
Docks Integration?

### ISSUE THREAD

**Issue by bgarrant** [bus-stop/Termination#68]
Any chance we can get this to work in Docks? It would be great if it was just next to the normal Diagnostics tab when open.  I noticed the original fork also does not have this feature.

![screen shot 2018-01-08 at 2 40 18 pm](https://user-images.githubusercontent.com/2436728/34689011-0f1c103c-f482-11e7-9a65-6b7ab0ab396d.png)

**Comment by Fred-Barclay** [comment]
Hi @bgarrant 
It would be awesome if this feature were added in 👍  -- unfortunately, at the moment I don't have time to actively develop it.

**Comment by the-j0k3r** [comment]
duplicate of #49

**Comment by the-j0k3r** [comment]
closed as duplicate
