### ISSUE TITLE
Add support for terminal panes

### ISSUE THREAD

**Issue by TristanBrotherton** [bus-stop/Termination#89]
Thank you for this fork and your hard work! 

I'd love to be able to have panes in termination, so I can have two terminals side by side ala iterm

**Comment by RenaKunisaki** [comment]
I'm not sure if this is the same thing, but I'd love to have a terminal as a "normal" editor tab.

**Comment by the-j0k3r** [comment]
Both [terminus](https://github.com/bus-stop/terminus) and [x-terminal](https://github.com/bus-stop/x-terminal) support this

**Comment by the-j0k3r** [comment]
Also duplicate of #49 closing
